$globaladmin = "admin.account@example.com"
$credentials = Get-Credential -Credential $globaladmin
Connect-MsolService -Credential $credentials


$user_email = read-host "What's the users email address?"
$email_from = "pwdnotify@example.com"
$email_to = "adminemail@example.com"
$email_subject = "Password for " + $user_email
$smtp_server = "yourorgsmtpserver.com"

$new_password = Set-MsolUserPassword -userprincipalname $user_email -NewPassword ""

$message = "<p>New password generated by admin for $user_email is: <b>$new_password</b></p>"

write-host "New password is: $new_password." 
write-host "Sending $email_to an Email..."
Send-MailMessage -From $email_from -To $email_to -Subject $email_subject -BodyAsHtml -Body ($message | out-string) -Priority High -DeliveryNotificationOption OnFailure -SmtpServer $smtp_server
write-host "Done."
